### ISSUE TITLE
edit page title display bug

### ISSUE THREAD

**Issue by hackerhui** [solariz/logseq-neon-theme#2]
When editing the page title, the title content is not displayed in the editing state
![屏幕截图 2022-07-14 080642](https://user-images.githubusercontent.com/42575324/178857485-0ad9dd32-320f-4537-be0c-65fcb4548906.png)

**Comment by solariz** [comment]
Thanks, I have some time in about 1-2 Weeks to go through all reports and try to fix them.

**Comment by solariz** [comment]
Fixed in 0.3
