### ISSUE TITLE
The code block obscures the previous line of text

### ISSUE THREAD

**Issue by chipsflying** [solariz/logseq-neon-theme#3]
![image](https://user-images.githubusercontent.com/102506599/189362597-4972fcae-8a24-470b-83ac-e0723635573a.png)
I like this theme very much. Thank you very much.
Currently learning the JavaScript and while taking notes I found that：
The code block obscures the previous line of text.

**Comment by solariz** [comment]
Thanks, I have some time in about 1-2 Weeks to go through all reports and try to fix them.

**Comment by solariz** [comment]
Fixed in 0.3

**Comment by chipsflying** [comment]
Thank you very much.
