### ISSUE TITLE
Cannot see 0.3 in marketplace

### ISSUE THREAD

**Issue by likayo** [solariz/logseq-neon-theme#4]
I have been using this theme full-time and am absolutely a fan of its feeling. I checked that this theme is updated to v0.3, but the marketplace still showed 0.2 as the latest version. I suspect that this is because the manifest is not updated: https://github.com/logseq/marketplace/tree/master/packages/logseq-neon-theme. Could you help upload the latest version?

**Comment by solariz** [comment]
Thanks, I pushed the marketplace manifest, hope it will pickup the changed version.
