### ISSUE TITLE
Fenced code blocks are overlapping other content

### ISSUE THREAD

**Issue by madclaws** [solariz/logseq-neon-theme#5]
Hi, i have been using this theme for few months, absolutely loving it, nice work :clap:. The only issue i am facing is when i try to add a `fenced code block` using **```**, the rendered block is overlapping other contents. Please let me know, if there is something we can do in css for fixing it or some other way. Thanks.
![Screenshot from 2022-10-31 05-13-58](https://user-images.githubusercontent.com/17821575/198907960-c4b0ecdf-33cb-4dd8-a390-78a6d0431ecf.png)

**Comment by solariz** [comment]
I just pushed v0.4 it should be in the updater in 24h hope it solve the issue completely. Let me know if not.

**Comment by madclaws** [comment]
Hi, it seems i was using an older version of the plugin.The inbuilt plugin update in logseq was not actually fetching latest update.
So i downloaded the code zip and loaded unpacked version. Now its updated and this problem is resolved.
Thanks a lot for the good work you are doing. :+1: . I am in love with this plugin :smile:
