### ISSUE TITLE
Title gets blurry after last two patch

### ISSUE THREAD

**Issue by lhz7788620** [solariz/logseq-neon-theme#6]
I believe after 0.8.8 patch i get this blurry title. before 0.8.7 all good. excerpt Daily journal title is good 
(I use custom.css don't know that may cause the issue)
Can you help, thank you so much, this theme is really fashion and fancy.
![title](https://user-images.githubusercontent.com/117700055/200460361-024eddcb-7732-4875-b76b-c7977601055e.png)

**Comment by solariz** [comment]
Yeah unfortunately noticed that by myself. Will check it later today, thanks for pointing out.

**Comment by solariz** [comment]
I just pushed v0.4 it should be in the updater in 24h hope it solve the issue completely. Let me know if not.

**Comment by lhz7788620** [comment]
It becomes clear but height of title seems a bit high and too big. (compare to other theme)
if with custom background, the title would jump out of the box. Can you make it smaller. 

![image](https://user-images.githubusercontent.com/117700055/200694259-30ce9778-2b5b-4b25-ae7a-9e4f7828a767.png)
Appreciate fast fix and support!

**Comment by lhz7788620** [comment]
My problem is solved after I removed some code about titles in custom.css which download from somewhere with the background.
Finally, can keep use my favorite theme in logseq. Thx very much author!
